Repository mivek/MetarParser, pull requests merged in 2019-02, with the labels that each got.

#62 Minor style enhancements
  .gitignore
  src/main/java/io/github/mivek/facade/MetarFacade.java
  src/main/java/io/github/mivek/facade/TAFFacade.java
Labels: clean

#64 Feature/cavok
  README.md
  pom.xml
  src/main/java/io/github/mivek/model/AbstractWeatherCode.java
  src/main/java/io/github/mivek/model/AbstractWeatherContainer.java
  src/main/java/io/github/mivek/parser/AbstractParser.java
  src/main/java/io/github/mivek/parser/TAFParser.java
  src/test/java/io/github/mivek/parser/MetarParserTest.java
  src/test/java/io/github/mivek/parser/TAFParserTest.java
Labels: enhancement

#66 Update regex for capital letters
  pom.xml
  src/main/java/io/github/mivek/model/AbstractWeatherContainer.java
  src/main/java/io/github/mivek/parser/AbstractParser.java
  src/main/java/io/github/mivek/parser/MetarParser.java
  src/main/java/io/github/mivek/parser/TAFParser.java
  src/test/java/io/github/mivek/parser/GeneralParseMetarTest.java
  src/test/java/io/github/mivek/parser/GeneralParseTAFTest.java
  src/test/java/io/github/mivek/parser/GeneralParseTest.java
Labels: refactor
